version: '3'

services:
  postgres:
    restart: always
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-sanity-check}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5434:5432'

volumes:
  pgdata:
